version: '3'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - '5416:5432'
    environment:
      POSTGRES_USER: heben
      POSTGRES_PASSWORD: zen
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local