version: '3'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - '5416:5432'
    environment:
      - POSTGRES_USER=heben
      - POSTGRES_PASSWORD=zen
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: api
    image: fredude/zen-api:latest
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/heben
      - SPRING_DATASOURCE_USERNAME=heben
      - SPRING_DATASOURCE_PASSWORD=zen
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION=true
      - SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT=20000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE=5
      - SERVER_ERROR_INCLUDE-MESSAGE=always

volumes:
  postgres-data:
    driver: local











